[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "axios>=0.4.0",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
]
